export enum Claims {
  // User
  VIEW_ALL_USER = 'VIEW_ALL_USER',

  // Role
  VIEW_ROLE_ALL = 'VIEW_ROLE_ALL',
  VIEW_ROLE_BY_ID = 'VIEW_ROLE_BY_ID',
  VIEW_ROLE_BY_NAME = 'VIEW_ROLE_BY_NAME',
  VIEW_CLAIMS = 'VIEW_CLAIMS',
  CREATE_ROLE = 'CREATE_ROLE',
  EDIT_ROLE = 'EDIT_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Role to user
  VIEW_ROLE_TO_USER_ALL = 'VIEW_ROLE_TO_USER_ALL',
  VIEW_ROLE_TO_USER_BY_ID = 'VIEW_ROLE_TO_USER_BY_ID',
  VIEW_ROLE_TO_USER_BY_USER_ID = 'VIEW_ROLE_TO_USER_BY_USER_ID',
  CREATE_ROLE_TO_USER = 'CREATE_ROLE_TO_USER',
  EDIT_ROLE_TO_USER = 'EDIT_ROLE_TO_USER',
  DELETE_ROLE_TO_USER = 'DELETE_ROLE_TO_USER',
}
